image:
  repository: "116143764563.dkr.ecr.us-east-1.amazonaws.com/payment-platform-reconciliation"
  tag: "latest"

serviceAccount:
  irsaRoleArn: "arn:aws:iam::116143764563:role/payment-platform-reconciliation-irsa"

env:
  - name: AWS_REGION
    value: "us-east-1"
  - name: WALLETS_TABLE
    value: "payment-platform-wallets"
  - name: RECONCILIATION_QUEUE_URL
    value: "https://sqs.us-east-1.amazonaws.com/116143764563/payment-platform-reconciliation-queue"
