image:
  repository: "116143764563.dkr.ecr.us-east-1.amazonaws.com/payment-platform-fraud-detection"
  tag: "latest"

serviceAccount:
  irsaRoleArn: "arn:aws:iam::116143764563:role/payment-platform-fraud-detection-irsa"

env:
  - name: AWS_REGION
    value: "us-east-1"
  - name: TRANSACTIONS_TABLE
    value: "payment-platform-transactions"
  - name: FRAUD_EVENTS_TABLE
    value: "payment-platform-fraud-events"
  - name: EVENT_BUS_NAME
    value: "payment-platform-events"
